.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. doriancoin_qt test_doriancoin_qt
clean: FORCE
	$(MAKE) -C .. doriancoin_qt_clean test_doriancoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_doriancoin_qt_check
doriancoin-qt doriancoin-qt.exe: FORCE
	 $(MAKE) -C .. doriancoin_qt
